---
title: "Emax data analysis"
author: "ccheng"
date: "January 4, 2016"
output: html_document
---

Emax data analysis

```{r, echo=FALSE}
library(ggplot2) #library for plotting
```


```{r dataload, echo=FALSE}
setwd("~/Documents/Programs/ODNP_Analysis/Rstudio")
#load data
df_Emax=read.csv(file="Emax.csv", header=TRUE, sep=',')
names(df_Emax)=c("Power","Integral")

df_Emax$Integral <- df_Emax$Integral/df_Emax$Integral[[1]] # normalization
MaxPower <- df_Emax$Power[length(df_Emax$Power)]
```


```{r EmaxFunction, echo=FALSE}
# function for NMR enhancement
f_E <- function(I0, A, B, P) {
    I0 - A*P/(1 + B*P)
}
# function for Emax
f_Emax <- function(I0, A, B){
    I0 - A/B  
}

fit_E <- nls(Integral~f_E(I0, A, B, Power), data=df_Emax, start=list(I0 =1, A=1, B=1))
#summary(fit_E)
parameter.est <- as.list(coef(fit_E))

```


```{r plot, echo=FALSE, fig.width=4, fig.height=3}
# simulated predicted profile at estimated parameter values
power_fitted <- seq(0, MaxPower*1.15, MaxPower*1.15/50)
fitted.data <- data.frame(x=power_fitted, y=predict(fit_E, list(Power = power_fitted )))

# plot
ggplot(df_Emax,aes(x=Power,y=Integral)) + 
  geom_point(color="red", size=3) + 
  scale_x_continuous(breaks=1:10) + 
  xlab("Power (Watt)")+ylab("peak integral") + 
  geom_line(data = fitted.data, aes(x=x, y=y), color ='blue', alpha=.5) 

# Emax data and standard deviation of Emax

Emax <- f_Emax(parameter.est$I0, parameter.est$A, parameter.est$B)

message("Emax = ", round(Emax, digits=3)) 

#I0 <- summary(fit_Emax)$coef[[1]]
#A <- summary(fit_Emax)$coef[[2]]
#B <- summary(fit_Emax)$coef[[2]]
#I0_SD <- summary(fit_Emax)$coef[[4]]
#A_SD <-summary(fit_Emax)$coef[[5]]
#B_SD <- summary(fit_Emax)$coef[[6]]

#Emax_SD <- ((D(expression(I0 - A/B), "I0")*summary(fit_Emax)$coef[[4]])^2 #+(D(expression(I0 - A/B), "A")*summary(fit_Emax)$coef[[5]])^2 +(D(expression(I0 - A/B), #"B")*summary(fit_Emax)$coef[[6]])^2)^0.5

#f_E_SD <- function(I0, A, B) {
#  ((D(expression(I0 - A/B), "I0")*I0_SD)^2 +(D(expression(I0 - A/B), "A")*A_SD)^2 #+(D(expression(I0 - A/B), "B")*B_SD)^2)^0.5
#}

```
