---
title: "ksigma data analysis"
author: "ccheng"
date: "January 4, 2016"
output: html_document
---

ksigma data analysis

```{r, echo=FALSE}
library(ggplot2) #library for plotting
```


```{r dataload, echo=FALSE}
setwd("~/Documents/Programs/ODNP_Analysis/Rstudio")
#spin-label concentration
CSL = 500*10^-6 # in Molar

#load Emax data 
df_Emax=read.csv(file="Emax.csv", header=TRUE, sep=',')
names(df_Emax)=c("Power","Integral")

df_Emax$Integral <- df_Emax$Integral/df_Emax$Integral[[1]] # normalization
MaxPower <- df_Emax$Power[length(df_Emax$Power)]

#load power vs T1 data
df_T1=read.csv(file="PowerVsT1.csv", header=TRUE, sep=',')
names(df_T1)=c("Power_T1","T1p", "T1p_error")

#T1_data
df_T1p <- df_T1[1:(length(df_T1$T1p)-1),]
MaxPower_T1 <- max(df_T1p$Power_T1)

#T10_data
T10 <- df_T1$T1p[length(df_T1$T1p)]
T10_SD <- df_T1$T1p_error[length(df_T1$T1p)]

```

```{r temp_calibration, echo=FALSE}

lm.cor = cor(df_T1p$Power_T1,df_T1p$T1p) # linear correlation

# if linear correlation <0.9, use 2nd order polynomial fit
if(lm.cor > 0.9){
   lmfit = lm(T1p~Power_T1, data=df_T1p)
} else {
   lmfit = lm(T1p ~ poly(Power_T1, 2, raw=TRUE), data=df_T1p)
}

#summary(lmfit)

# simulated predicted profile at estimated parameter values
power_x <- data.frame(Power_T1=seq(0, MaxPower_T1*1.1, MaxPower_T1*1.1/50))
fitted.T1data <- predict(lmfit, newdata=power_x, se.fit = TRUE)

power_x$lci <- fitted.T1data$fit - 1.96 * fitted.T1data$se.fit
power_x$fit <- fitted.T1data$fit
power_x$uci <- fitted.T1data$fit + 1.96 * fitted.T1data$se.fit

ggplot(power_x, aes(x = Power_T1, y = fit)) +
  theme_bw() +
  geom_line() +
  geom_smooth(aes(ymin = lci, ymax = uci), stat = "identity") +
  geom_point(data=df_T1p, aes(x=Power_T1, y=T1p), color="red", size=3) +
  xlab("MW power (Watt)") +
  ylab("T1 (s)")

```


```{r krho, echo=FALSE}
# function for krho
f_krho <- function(T1, T10, CSL) {
    (1/T1-1/T10)/CSL
}
krho <- f_krho(df_T1p$T1p[1],T10,CSL) # in 1/M/sec
```


```{r ksigmaPlot, echo=FALSE}
# function for ksigma
f_sigma <- function(En, CSL, T1cor) {
    (1-En)/CSL/T1cor/658
}

# function for ksigma*smax
f_sigmasmax <-  function(A, B, P) {
    A*P/(B+P)
}

Power_T1_list <- data.frame(Power_T1=df_Emax$Power)
T1cor <- predict(lmfit, newdata=Power_T1_list)

ksigma_list <- f_sigma(df_Emax$Integral, CSL, T1cor)

df_ksigma <- data.frame(Power=df_Emax$Power, ksigma = ksigma_list)
  
ggplot(df_ksigma,aes(x=Power,y=ksigma)) + geom_point(color="red", size=3)

fit_ksimga <- nls(ksigma ~ f_sigmasmax(A, B, Power), data=df_ksigma, start=list(A=100, B=1))

#summary(fit_ksimga)
parameter.est <- as.list(coef(fit_ksimga))

# simulated predicted profile at estimated parameter values
power_1 <- seq(0, max(df_ksigma$Power)*1.1, max(df_ksigma$Power)*1.1/50)
fitted.ksigma <- data.frame(x=power_1, y=predict(fit_ksimga, list(Power = power_1 )))

# plot
ggplot(df_ksigma,aes(x=Power,y=ksigma)) + 
  geom_point(color="red", size=3) + 
  scale_x_continuous(breaks=1:10) + 
  xlab("Power (Watt)")+ylab("ksigma*smax") + 
  geom_line(data = fitted.ksigma, aes(x=x, y=y), color ='blue', alpha=.5) 

# ksigma data and standard deviation of ksigma

ksigma<- parameter.est$A

message("ksigma = ", round(ksigma, digits=3) , " 1/M/sec") 

```

```{r klow, echo=FALSE }

# function klow
f_klow <-  function(krho, ksimga) {
    (5/3)*krho - (7/3)*ksigma
}

klow = f_klow(krho,ksigma)
klow
```

```{r rho, echo=FALSE}


```